/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and dependency status
         * @description Report whether the API can actually serve requests.
         *
         *     Deliberately does **not** use the repository dependency: that dependency opens a
         *     connection, so a database outage would fail before the handler ran and return a
         *     generic 503 with no detail about which component is down. The check owns its own
         *     connection so it can report precisely.
         *
         *     Returns 503 when the database is unreachable or a required table is missing, because
         *     a monitoring system needs the status code - a body saying "unhealthy" behind a 200 is
         *     not actionable.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detected anomalies
         * @description Paginated anomalies, worst severity first, then most recent.
         *
         *     ``total`` is the unpaginated count, so a client can show "23 of 1,204" rather than
         *     discovering the end of the list by walking off it.
         */
        get: operations["list_anomalies_anomalies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Documented failure events
         * @description The four maintenance reports published with the dataset, verbatim.
         *
         *     Each carries its lead-up data usability. Event #1's 24-hour run-up is 69.5% held
         *     data, so any statistic computed over it would describe a frozen logger rather than a
         *     compressor - the API says so rather than leaving a consumer to find out.
         */
        get: operations["list_failures_failures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything the overview screen needs
         * @description One round trip for the whole Overview.
         *
         *     A dashboard that fires eight requests to draw one screen is slower and harder to
         *     reason about than one endpoint answering the question the screen actually asks.
         */
        get: operations["get_summary_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Archive quality at a glance
         * @description Coverage, trust and ingestion recency.
         *
         *     ``held_readings`` is the number that matters and the one no standard check would
         *     surface: values from a data-acquisition freeze are non-null and inside range, so both
         *     a null check and a range check pass them.
         */
        get: operations["get_data_quality_data_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List equipment
         * @description Every monitored asset, with its active sensor count.
         */
        get: operations["list_equipment_equipment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipment/{equipment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one piece of equipment */
        get: operations["get_equipment_equipment__equipment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipment/{equipment_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current health of one piece of equipment
         * @description Health over a trailing window, not over all history.
         *
         *     Anomalies are counted across the last 24 hours of the archive. A status that only
         *     accumulates can never return to NORMAL, which makes it a history rather than a
         *     status.
         */
        get: operations["get_equipment_health_equipment__equipment_id__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sensors
         * @description Sensor definitions, including the verbatim description from the dataset docs.
         */
        get: operations["list_sensors_sensors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one sensor */
        get: operations["get_sensor_sensors__sensor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readings/{sensor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historical readings for one sensor
         * @description Return a series, choosing a resolution that a client can actually draw.
         *
         *     The response always states the resolution it served and whether a cap was hit, so a
         *     truncated series can never be mistaken for a complete one.
         */
        get: operations["get_readings_readings__sensor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trends/{sensor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trend with rolling statistics
         * @description Hourly series with a rolling mean, rolling spread and rate of change.
         *
         *     Rate of change is per hour of **elapsed** time rather than per bucket, because 17.6%
         *     of the archive is missing: treating a 48-hour gap as one step would report a violent
         *     swing where there was simply no data.
         */
        get: operations["get_trend_trends__sensor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readings for several sensors at once
         * @description Fetch several series in one round trip, for a multi-tag chart.
         *
         *     Capped at eight sensors. The point cap is per series, so an uncapped list would let a
         *     single request ask for 15x the ceiling.
         */
        get: operations["get_multi_readings_readings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Result caps applied by this API
         * @description Publish the caps rather than letting clients discover them by being truncated.
         */
        get: operations["get_limits_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AggregatePoint
         * @description One bucket of an aggregated series.
         */
        AggregatePoint: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Value
             * @description Mean over the bucket.
             */
            value: number;
            /** Min Value */
            min_value: number;
            /** Max Value */
            max_value: number;
            /** Sample Count */
            sample_count: number;
            /**
             * Coverage Pct
             * @description Samples present as a percentage of a fully-covered bucket at the measured 10 s interval. The archive is 82.4% covered overall, so many buckets hold fewer samples than a naive reader would assume.
             */
            coverage_pct?: number | null;
        };
        /** Anomaly */
        Anomaly: {
            /** Anomaly Id */
            anomaly_id: number;
            /** Sensor Id */
            sensor_id: number;
            /** Sensor Code */
            sensor_code: string;
            /** Sensor Name */
            sensor_name: string;
            /** Equipment Code */
            equipment_code: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Value */
            value: number;
            /** Unit */
            unit?: string | null;
            /** Expected Low */
            expected_low?: number | null;
            /** Expected High */
            expected_high?: number | null;
            /**
             * Method
             * @description Which rule fired. The same instant may be flagged by more than one.
             */
            method: string;
            /** Score */
            score: number;
            severity: components["schemas"]["Severity"];
            operating_state?: components["schemas"]["OperatingState"] | null;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
        };
        /** AnomalyPage */
        AnomalyPage: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["Anomaly"][];
        };
        /** ComponentHealth */
        ComponentHealth: {
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "up" | "down" | "degraded";
            /** Detail */
            detail?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
        };
        /** DataQualitySummary */
        DataQualitySummary: {
            /** Total Readings */
            total_readings: number;
            /** Good Readings */
            good_readings: number;
            /** Good Pct */
            good_pct: number;
            /**
             * Held Readings
             * @description Readings from a data-acquisition freeze: every analogue signal repeating the previous scan. Plausible, in range, not measurements.
             */
            held_readings: number;
            /** Held Pct */
            held_pct: number;
            /** Quarantined Rows */
            quarantined_rows: number;
            /** Gap Count */
            gap_count: number;
            /** Coverage Pct */
            coverage_pct: number;
            /** Last Successful Ingestion */
            last_successful_ingestion: string | null;
            /** Last Ingestion Status */
            last_ingestion_status: string | null;
        };
        /** Equipment */
        Equipment: {
            /** Equipment Id */
            equipment_id: number;
            /** Equipment Code */
            equipment_code: string;
            /** Equipment Name */
            equipment_name: string;
            /** Equipment Type */
            equipment_type: string;
            /** Location */
            location?: string | null;
            /** Description */
            description?: string | null;
            /** Sensor Count */
            sensor_count: number;
            /** Is Active */
            is_active: boolean;
        };
        /** EquipmentHealth */
        EquipmentHealth: {
            /** Equipment Id */
            equipment_id: number;
            /** Equipment Code */
            equipment_code: string;
            /** Equipment Name */
            equipment_name: string;
            status: components["schemas"]["HealthStatus"];
            /**
             * Status Reason
             * @description Plain-language explanation. A status an operator cannot act on is not a status.
             */
            status_reason: string;
            /** Sensor Count */
            sensor_count: number;
            /** Last Reading At */
            last_reading_at: string | null;
            /** Total Readings */
            total_readings: number;
            /** Active Critical Anomalies */
            active_critical_anomalies: number;
            /** Active Warning Anomalies */
            active_warning_anomalies: number;
            /** Recorded Failures */
            recorded_failures: number;
            /**
             * Active Window Hours
             * @description Anomalies are counted over this trailing window of the archive, not over all history - a status that only accumulates can never return to NORMAL.
             * @default 24
             */
            active_window_hours: number;
        };
        /** FailureEvent */
        FailureEvent: {
            /** Failure Event Id */
            failure_event_id: number;
            /** Equipment Id */
            equipment_id: number;
            /** Equipment Code */
            equipment_code: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Duration Minutes */
            duration_minutes: number;
            /** Failure Type */
            failure_type: string;
            /** Severity */
            severity: string;
            /**
             * Source Reference
             * @description The identifier used in the published failure table, verbatim - including its known defects.
             */
            source_reference?: string | null;
            /** Report Note */
            report_note?: string | null;
            /** Data Quality Note */
            data_quality_note?: string | null;
            /** Lead Up 24H Scans */
            lead_up_24h_scans?: number | null;
            /** Lead Up 24H Stale Scans */
            lead_up_24h_stale_scans?: number | null;
            /** Lead Up 24H Stale Pct */
            lead_up_24h_stale_pct?: number | null;
            /**
             * Lead Up Usability
             * @description USABLE, UNUSABLE or NO DATA. Event #1's run-up is 69.5% held data, so any statistic computed over it would describe a frozen logger.
             */
            lead_up_usability?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness plus dependency status.
         *
         *     Returns 200 when the API itself is serving and 503 when a dependency it cannot work
         *     without is unavailable. A monitoring system needs that distinction; a body that says
         *     "unhealthy" behind a 200 is not actionable.
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "degraded" | "unhealthy";
            /** Version */
            version: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Components */
            components: components["schemas"]["ComponentHealth"][];
        };
        /**
         * HealthStatus
         * @enum {string}
         */
        HealthStatus: "NORMAL" | "WARNING" | "CRITICAL" | "NO DATA";
        /** LatestReading */
        LatestReading: {
            /** Sensor Id */
            sensor_id: number;
            /** Sensor Code */
            sensor_code: string;
            /** Sensor Name */
            sensor_name: string;
            /** Sensor Class */
            sensor_class: string;
            /** Unit */
            unit: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Value */
            value: number;
            /** Quality */
            quality: string;
            /** Quality Usable */
            quality_usable: boolean;
        };
        /**
         * OperatingState
         * @enum {string}
         */
        OperatingState: "OFF" | "OFFLOADED" | "LOADED" | "STARTING";
        /**
         * ProblemDetail
         * @description RFC 7807 problem details.
         *
         *     A machine-readable error shape, so a client can branch on ``type`` rather than
         *     pattern-matching prose that will be reworded eventually.
         * @example {
         *       "detail": "start (2020-06-01T00:00:00) must be earlier than end (2020-05-01T00:00:00).",
         *       "instance": "/readings/14",
         *       "status": 422,
         *       "title": "Invalid time range",
         *       "type": "/problems/invalid-time-range"
         *     }
         */
        ProblemDetail: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /** Instance */
            instance?: string | null;
        };
        /**
         * ReadingPoint
         * @description One point of a raw series.
         */
        ReadingPoint: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Value */
            value: number;
            /** Quality */
            quality: string;
            /** Quality Usable */
            quality_usable: boolean;
        };
        /** ReadingSeries */
        ReadingSeries: {
            /** Sensor Id */
            sensor_id: number;
            /** Sensor Code */
            sensor_code: string;
            /** Unit */
            unit: string | null;
            /** @description The resolution actually served, which may differ from the one requested when 'auto' was used or when a cap was applied. */
            resolution: components["schemas"]["Resolution"];
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Point Count */
            point_count: number;
            /**
             * Truncated
             * @description True when a result cap was reached and the series is incomplete. Never silently trimmed.
             * @default false
             */
            truncated: boolean;
            /** Points */
            points?: components["schemas"]["ReadingPoint"][];
            /** Aggregates */
            aggregates?: components["schemas"]["AggregatePoint"][];
        };
        /**
         * Resolution
         * @description Time resolution of a series.
         *
         *     ``AUTO`` lets the server choose based on the requested window, which is what stops a
         *     six-month request from trying to return 1.8 million points per sensor.
         * @enum {string}
         */
        Resolution: "auto" | "raw" | "hourly" | "daily";
        /** Sensor */
        Sensor: {
            /** Sensor Id */
            sensor_id: number;
            /** Equipment Id */
            equipment_id: number;
            /** Sensor Code */
            sensor_code: string;
            /** Sensor Name */
            sensor_name: string;
            /**
             * Sensor Class
             * @enum {string}
             */
            sensor_class: "Analogue" | "Digital";
            /** Measurement Type */
            measurement_type: string;
            /** Unit */
            unit?: string | null;
            /** Physical Min */
            physical_min?: number | null;
            /** Physical Max */
            physical_max?: number | null;
            /**
             * Documented Setpoint
             * @description A setpoint published by the equipment owner (e.g. the 7 bar low-pressure switch), not a threshold chosen by this project.
             */
            documented_setpoint?: number | null;
            /**
             * Description
             * @description Verbatim description from the dataset documentation.
             */
            description: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "NORMAL" | "WARNING" | "CRITICAL";
        /**
         * SystemSummary
         * @description Everything the Overview screen needs, in one call.
         *
         *     Deliberately one round trip: a dashboard that fires eight requests to render one
         *     screen is slower and harder to reason about than one endpoint that answers the
         *     question the screen actually asks.
         */
        SystemSummary: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Archive Start */
            archive_start: string | null;
            /** Archive End */
            archive_end: string | null;
            /** Equipment Count */
            equipment_count: number;
            /** Sensor Count */
            sensor_count: number;
            /** Equipment */
            equipment: components["schemas"]["EquipmentHealth"][];
            /** Latest Readings */
            latest_readings: components["schemas"]["LatestReading"][];
            /** Active Anomalies */
            active_anomalies: components["schemas"]["Anomaly"][];
            /** Recent Failures */
            recent_failures: components["schemas"]["FailureEvent"][];
            data_quality: components["schemas"]["DataQualitySummary"];
        };
        /** TrendPoint */
        TrendPoint: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Value */
            value: number;
            /** Rolling Mean */
            rolling_mean?: number | null;
            /** Rolling Std */
            rolling_std?: number | null;
            /** Rate Of Change Per Hour */
            rate_of_change_per_hour?: number | null;
            /** Sample Count */
            sample_count: number;
        };
        /** TrendSeries */
        TrendSeries: {
            /** Sensor Id */
            sensor_id: number;
            /** Sensor Code */
            sensor_code: string;
            /** Unit */
            unit: string | null;
            /** @description When set, the trend covers only periods in this operating state. The compressor is off 54.65% of the time, so a state-blind trend blends idle and running behaviour into a number describing neither. */
            operating_state?: components["schemas"]["OperatingState"] | null;
            /** Window Hours */
            window_hours: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Point Count */
            point_count: number;
            /** Points */
            points: components["schemas"]["TrendPoint"][];
            /** Summary */
            summary?: {
                [key: string]: number | null;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description A required dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_anomalies_anomalies_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                sensor_id?: number | null;
                severity?: components["schemas"]["Severity"] | null;
                /** @description ADAPTIVE_MAD, BASELINE_IQR or SETPOINT. The same instant can be flagged by more than one rule, so filtering by method answers 'which rule fired' rather than collapsing them. */
                method?: string | null;
                /** @description Maximum items to return. */
                limit?: number;
                /** @description Items to skip, for pagination. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyPage"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_failures_failures_get: {
        parameters: {
            query?: {
                equipment_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailureEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSummary"];
                };
            };
        };
    };
    get_data_quality_data_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualitySummary"];
                };
            };
        };
    };
    list_equipment_equipment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Equipment"][];
                };
            };
        };
    };
    get_equipment_equipment__equipment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Equipment"];
                };
            };
            /** @description No such resource */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_equipment_health_equipment__equipment_id__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentHealth"];
                };
            };
            /** @description No such resource */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sensors_sensors_get: {
        parameters: {
            query?: {
                equipment_id?: number | null;
                sensor_class?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sensor"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sensor_sensors__sensor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric id or sensor code, e.g. 15 or TP3. */
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sensor"];
                };
            };
            /** @description No such resource */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_readings_readings__sensor_id__get: {
        parameters: {
            query?: {
                /** @description Inclusive start of the window (ISO 8601). Defaults to the end of the archive minus the default window. */
                start?: string | null;
                /** @description Exclusive end of the window (ISO 8601). */
                end?: string | null;
                /** @description 'auto' picks raw / hourly / daily from the width of the window. Ask for a specific resolution only if you need it - six months of raw data is 1.8 million points. */
                resolution?: components["schemas"]["Resolution"];
            };
            header?: never;
            path: {
                /** @description Numeric id or sensor code, e.g. 15 or TP3. */
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingSeries"];
                };
            };
            /** @description No such sensor */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Invalid time range */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_trend_trends__sensor_id__get: {
        parameters: {
            query?: {
                /** @description Inclusive start of the window (ISO 8601). Defaults to the end of the archive minus the default window. */
                start?: string | null;
                /** @description Exclusive end of the window (ISO 8601). */
                end?: string | null;
                /** @description Restrict the trend to one operating state. Strongly recommended for anything statistical: the compressor is off 54.65% of the time, so a state-blind mean blends idle and running behaviour. */
                operating_state?: components["schemas"]["OperatingState"] | null;
                /** @description Rolling window, in hourly buckets. */
                window_hours?: number;
            };
            header?: never;
            path: {
                /** @description Numeric id or sensor code. */
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendSeries"];
                };
            };
            /** @description No such sensor */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Invalid time range */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_multi_readings_readings_get: {
        parameters: {
            query: {
                /** @description Comma-separated sensor ids or codes, e.g. 'TP2,TP3,OIL_TEMPERATURE'. */
                sensors: string;
                /** @description Inclusive start of the window (ISO 8601). Defaults to the end of the archive minus the default window. */
                start?: string | null;
                /** @description Exclusive end of the window (ISO 8601). */
                end?: string | null;
                resolution?: components["schemas"]["Resolution"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingSeries"][];
                };
            };
            /** @description No such sensor */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Invalid time range */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_limits_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number | string;
                    };
                };
            };
        };
    };
}
